name: "Feature Request"
description: "Propose a new feature to this repo"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        What issue does this feature solve?
        - Given
        - When
        - Then
      
