name: Dependabot Labeler

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply labels by semver
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            dependencies
            ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' && 'semver:patch' || '' }}
            ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' && 'semver:minor' || '' }}
            ${{ steps.metadata.outputs.update-type == 'version-update:semver-major' && 'semver:major' || '' }}
